### ISSUE TITLE
dependence problem with `cl`

### ISSUE THREAD

**Issue by rvelseg** [chachi/cuda-mode#1]
Current version on MELPA (cuda-mode-20140704.1357) has a dependence problem with `cl-macroexpand-all`, this issue has been observed in other packages, indeed by now a simple workarround is described in the following question http://emacs.stackexchange.com/questions/2864

Thanks for the mode, it has been very useful for me.

**Comment by chachi** [comment]
Thanks for reporting! I'll change to the `macroexpand-all` and push the change.

**Comment by chachi** [comment]
Actually, I'm not seeing where this problem happens. What version of Emacs are you using and where does the problem occur exactly?
