### ISSUE TITLE
Error: Invalid function 0

### ISSUE THREAD

**Issue by zhengyang92** [chachi/cuda-mode#6]
Hi  Jack Morrison

I am trying cuda-mode on self-compiled gnu-emacs 24.5.1. When I load a *.cu file emacs throws a error(Invalid function 0), traceback shows the error code is at https://github.com/chachi/cuda-mode/blob/master/cuda-mode.el#L285 . It seems that emacs tries to eval (0 'font-lock-builtin-face). Could you check if there's mistake :-)

Thanks.

**Comment by chachi** [comment]
Yes, you're very right. I'll fix that ASAP. Thanks for pointing it out!

**Comment by chachi** [comment]
Okay, fix pushed. Undoes last PR.

**Comment by zhengyang92** [comment]
Thank you
